#!/usr/bin/env python3
"""Generate .review/boss-inventory.md — one row per boss module.

Read-only. Run from the repository root:  python3 .review/inventory.py
"""

import os
import re
import sys


def mod_files(root):
    out = []
    for base, dirs, files in os.walk(os.path.join(root, "trial")):
        if "boss" not in base.split(os.sep):
            continue
        for f in sorted(files):
            if f.endswith(".lua"):
                out.append(os.path.relpath(os.path.join(base, f), root))
    return sorted(out)


def read(root, rel):
    return open(os.path.join(root, rel), encoding="utf-8", errors="replace").read()


def block(src, pattern):
    m = re.search(pattern + r"\s*=\s*\{", src)
    if not m:
        return ""
    i, depth = m.end() - 1, 0
    while i < len(src):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return src[m.end():i]


def entries(body):
    body = re.sub(r"--[^\n]*", "", body)
    return re.findall(r"^\s*\[([^\]]+)\]\s*=", body, re.M)


def main():
    root = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else ".")
    rows = []
    for rel in mod_files(root):
        src = read(root, rel)
        name = re.search(r"\.name\s*=\s*\"([^\"]*)\"", src)
        aliases = re.findall(r"\.nameAliases\s*=\s*\{([^}]*)\}", src)
        alias = ", ".join(re.findall(r"\"([^\"]+)\"", aliases[0])) if aliases else ""
        loc = re.search(r"\.location\s*=\s*(Location\.new\([^)]*\)|nil)", src)
        thr = re.search(r"\.hmHealthThreshold\s*=\s*([0-9A-Za-z_.]+)", src)
        schema = block(src, r"\.stateSchema")
        fields = len(re.findall(r"^\s*[A-Za-z_]\w*\s*=", schema, re.M))
        comb = entries(block(src, r"\.combatRoutes"))
        eff = entries(block(src, r"\.effectRoutes"))
        slots = sorted({int(s) for s in re.findall(r"showInfo\(\s*(\d+)", src)})
        hooks = [h for h in ("onEnter", "onLeave", "onWipe", "onCombatState",
                             "onPowerUpdate", "onDied", "onUpdate")
                 if re.search(r"function\s+\w+[:.]" + h + r"\b", src)]
        common = re.search(r"\.common\s*=\s*(\w+)", src)
        todos = len(re.findall(r"\bTODO\b", src))
        rows.append({
            "file": rel,
            "lines": src.count("\n") + 1,
            "key": (re.search(r"\.key\s*=\s*\"([^\"]*)\"", src) or [None, "?"])[1],
            "name": name.group(1) if name else "",
            "aliases": alias,
            "location": loc.group(1) if loc else "—",
            "threshold": thr.group(1) if thr else "—",
            "fields": fields,
            "combat": len(comb),
            "effect": len(eff),
            "slots": ("1-%d" % max(slots)) if slots else "—",
            "hooks": " ".join(h.replace("on", "").replace("CombatState", "CS")
                              .replace("PowerUpdate", "PU") for h in hooks) or "—",
            "common": common.group(1) if common else "—",
            "todos": todos,
        })

    print("# Boss module inventory")
    print()
    print("Generated by `.review/inventory.py` from commit `%s`. Read-only."
          % os.popen("git -C %s rev-parse --short HEAD" % root).read().strip())
    print()
    print("`fields` = stateSchema entries, `C/E` = combatRoutes/effectRoutes entries, "
         "`slots` = info lines written by the display loop, "
         "`hooks` = lifecycle methods implemented (Ent, Le, Wipe, CS, PU, Died, Upd).")
    print()
    print("| file | lines | key | detection | HM threshold | fields | C/E | slots | hooks | common | TODO |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        detect = r["location"] if r["location"] != "—" else (
            "name: " + r["name"] if r["name"] else
            "aliases: " + (r["aliases"] or "NONE"))
        print("| `%s` | %d | %s | %s | %s | %d | %d/%d | %s | %s | %s | %d |"
              % (r["file"], r["lines"], r["key"], detect, r["threshold"],
                 r["fields"], r["combat"], r["effect"], r["slots"], r["hooks"],
                 r["common"], r["todos"]))
    print()
    tot = {k: sum(r[k] for r in rows) for k in ("lines", "fields", "combat", "effect", "todos")}
    print("**Totals** — %d boss modules, %d lines, %d stateSchema fields, "
          "%d combatRoutes + %d effectRoutes entries, %d TODO markers."
          % (len(rows), tot["lines"], tot["fields"], tot["combat"], tot["effect"],
             tot["todos"]))
    unhooked = [r["file"] for r in rows if "Le" not in r["hooks"]]
    unwipe = [r["file"] for r in rows if "Wipe" not in r["hooks"]]
    nodetect = [r["file"] for r in rows if r["location"] == "—" and not r["name"] and not r["aliases"]]
    print()
    print("* no `onLeave`: %s" % (", ".join("`%s`" % f for f in unhooked) or "none"))
    print("* no `onWipe`: %s" % (", ".join("`%s`" % f for f in unwipe) or "none"))
    print("* no detection rule at all (no location, no name, no aliases): %s"
          % (", ".join("`%s`" % f for f in nodetect) or "none"))


if __name__ == "__main__":
    main()
